version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/tracker
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - mongo
      - flask_app

  flask_app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "6500:6500"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/tracker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
    - "3000:3000"
    restart: always

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

